# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: "../config/samples.tsv"

ref:
  index: "/home/minimind/Escritorio/snakemake_local/GRCh38_index/Homo_sapiens_assembly38.fasta.64"   # the BWA index
  hla: "/home/minimind/Escritorio/snakemake_local/extra_files/hla_reference_dna.fasta" #Necessary file to preprocess for optitype
  #optitype: "/home/julia/Escritorio/Bioinformatica_II/TFM/snakemake_final/extra_files/config.ini" #config.ini file of otitype to indicate the number of threads

gatk:
  fasta: "/home/minimind/Escritorio/snakemake_local/GRCh38/Homo_sapiens_assembly38.fasta"
  dict: "/home/minimind/Escritorio/snakemake_local/GRCh38/Homo_sapiens_assembly38.dict"
  known: "/home/minimind/Escritorio/snakemake_local/extra_files/1000G_omni2.5.hg38.vcf.gz"
  intervals: "/home/minimind/Escritorio/snakemake_local/config/VC_positions_chr_sorted_0.bed"
  dbsnp: "/home/minimind/Escritorio/snakemake_local/dbSNP/Homo_sapiens_assembly38.dbsnp138.vcf"

mosdepth:
  bed: "/home/minimind/Escritorio/snakemake_local/extra_files/positions_coverage.bed"
  
picard: "/home/minimind/Software"

report:
  variants: "/home/minimind/Escritorio/snakemake_local/config/variants_sorted_0.bed"
